Функция конвертации валют
RomanKovalenko61/js-basic pull request #2
Opened 2024-04-30 14:09 UTC by RomanKovalenko61

2024-05-02 07:53 UTC, GitEsense requested changes
`7-converter` - `OK!`
`8-crypto` - `OK!`
`9-sort-loops` - ` NOT OK!` - Необходимо внести исправление (исходный массив не должен быть модифицирован), после всех манипуляций сортировки, исходный массив так и должен быть "первоначальным", пример

```js
const arr = [5,3,2,4,1]
console.log(arr) // [5,3,2,4,1]
console.log(sortAsc(arr)) // [1,2,3,4,5]
console.log(sortDesc(arr)) // [5,4,3,2,1]
console.log(arr) // [5,3,2,4,1]
```

2024-05-02 07:53 UTC, GitEsense commented on 7-converter/app.js
> +console.log(`1000 рублей в йены ${converter(1000, "USD", "YEN")}`);
Функционально работает и всё окей, но давайте предложу вот такие вот варианты на рассмотрение:
**Вариант №1:**
```js
function converter(sum, currency, targetCurrency) {
    const USD = 90;
    const EUR = 100;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * USD;
                case 'EUR':
                    return (sum * USD) / EUR;
                default:
                    return null;
            }
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * EUR;
                case 'USD':
                    return (sum * EUR) / USD;
                default:
                    return null;
            }
        case 'RUB':
            switch (targetCurrency) {
                case 'USD':
                    return sum / USD;
                case 'EUR':
                    return sum / EUR;
                default:
                    return null;
            }
        default:
            return null;
    }
}
```

**Вариант №2:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = ['RUB', 'EUR', 'USD'];
    const USD = 91.33;
    const RUB = 1;
    const EUR = 112.33;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();
    const icon = getTargetCurrencyIcon(targetCurrency);

    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }
    if (!ALLOW_CURRENCY_LIST.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!ALLOW_CURRENCY_LIST.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    
    let value = null;

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, USD, RUB); break;
                case 'EUR': value = convertSum(sum, USD, EUR); break;
            }; break;
        case 'RUB':
            switch (targetCurrency) {
                case 'USD': value = convertSum(sum, RUB, USD); break;
                case 'EUR': value = convertSum(sum, RUB, EUR); break;
            }; break;
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, EUR, RUB); break;
                case 'USD': value = convertSum(sum, EUR, USD); break;
            }; break;
    }

    return messageTemplate(value, icon)
}
```

**Вариант №3:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = [['RUB', 1], ['EUR', 112.33], ['USD', 91.33]];
    const flatList = ALLOW_CURRENCY_LIST.flat();
    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    if (!flatList.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!flatList.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    const icon = getTargetCurrencyIcon(targetCurrency);
    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }

    const currentIndex = flatList.indexOf(currency) / 2;
    const targetIndex = flatList.indexOf(targetCurrency) / 2;
    const [, currentValue] = ALLOW_CURRENCY_LIST[currentIndex];
    const [, targetValue] = ALLOW_CURRENCY_LIST[targetIndex];
    const result = convertSum(sum, currentValue, targetValue)
    return messageTemplate(result, icon);
}
```

2024-05-02 07:53 UTC, GitEsense commented on 8-crypto/app.js
> +        }
Вот тут можно сделать "симпатичнее" с приёмом "обмена переменных", тем более, что temp не существует до момента объявления
```js
if(arr[i] && arr[i+1]){
   [arr[i], arr[i + 1]] = [arr[i + 1], arr[i]]
}
```

2024-05-02 07:53 UTC, GitEsense commented on 8-crypto/app.js
> +}
Вот тут можно сделать объединение check2 функции и check
```js
function check(cryptedWord, checkWord) {
    if(!cryptedWord || !checkWord){
        return false
    }
    return checkWord === crypto(cryptedWord) ? true : false;
}

2024-05-02 07:53 UTC, GitEsense commented on 8-crypto/app.js
> +);
А вот так можно сделать, если соответствовать строго "шаблону", описанному в конспекте
```js
function crypto(password) {
    if (!password) {
        return false;
    }
    const splitedArray = password.split('');
    if (splitedArray.length < 8) {
        return false;
    }

    const middleIndex = Math.floor(splitedArray.length / 2);
    const firstHalf = splitedArray.slice(0, middleIndex).reverse();
    const secondHalf = splitedArray.slice(middleIndex).reverse();
    const length = secondHalf.length;
    [secondHalf[1], secondHalf[length - 2]] = [secondHalf[length - 2], secondHalf[1]];

    const encryptedPassword = firstHalf.concat(secondHalf);
    return encryptedPassword.join('');
}

function check(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypto(encryptedPassword);
}
```

2024-05-02 07:53 UTC, GitEsense commented on 9-sort-loops/app.js
> +}
Вы модифицируете исходный массив, т.е. после вызова 
```js
console.log("Первоначальный массив " + arr); // arr = [1, 40, -5, 10, 0]
console.log("Отсортированный по возрастанию " + greedySort(arr, 0));
console.log("Первоначальный массив " + arr); // arr = [-5, 0 1, 10, 40]
console.log("Отсортированный по убыванию " + greedySort(arr, 1));
console.log("Первоначальный массив " + arr); // arr = []
```

Вам необходимо реализовать без модификации исходного массива

Оптимизировать Ваше решение можно вот таким вариантом например ( я тут нарочно убрал "ответ" о модификации, поэтому предложенный вариант так же модифицирует исходный массив):
```js
function orderTemplate(firstNumber, secondNumber, desc) {
    if (!desc) {
        return firstNumber > secondNumber;
    }
    return firstNumber < secondNumber;
}

function sortArrayInAscending(array, desc = false) {
    for (let i = 0; i < array.length; i++) {
        for (let j = i; j < array.length; j++) {
            const isExchange = orderTemplate(array[i], array[j], desc);
            if (isExchange) {
                [array[i], array[j]] = [array[j], array[i]];
            }
        }
    }
    return array;
}

2024-05-09 15:49 UTC, RomanKovalenko61 commented on 9-sort-loops/app.js
> +}
Мне кажется можно сделать j = i + 1. убрать сравнение числа с самим собой на каждой итерации внешнего цикла

2024-05-10 12:43 UTC, GitEsense commented on 9-sort-loops/app.js
> +}
> Мне кажется можно сделать j = i + 1. убрать сравнение числа с самим собой на каждой итерации внешнего цикла

Можно, почему нет, тогда итераций будет уже не 15, а 10

2024-05-10 12:44 UTC, GitEsense approved these changes
Теперь всё ок)

2024-05-10 13:12 UTC, merged